# This file was generated by GoReleaser. DO NOT EDIT.
cask "unarr" do
  version "1.3.9-beta"

  on_macos do
    on_intel do
      sha256 "ff11ef4f6f0638f4fd7ffca81059093007ec46b747d3dcb2947221c8614de77c"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "197281f47e36efb876cb124a7f45e283f007960cd7b953646480c6807510fe1f"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c88161ba4efa48436530f2c8c7b0a0fc9eb5e6fdfe5547c3641d62fad7182131"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "551d96fe2c4832d679f5ad1cc3eaa5f00b8ae9b0a949c756c83cc96e83888b13"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "unarr"
  desc "Self-hosted media manager, player and debrid agent CLI"
  homepage "https://unarr.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unarr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
