# This file was generated by GoReleaser. DO NOT EDIT.
cask "unarr" do
  version "1.5.3"

  on_macos do
    on_intel do
      sha256 "caf2ec572ddef8a9985ed994b6a28bbb57a9be710882d27c6797aafa5aae164f"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "813f216e6605fd46fdc8dff4aabbdb14ae16a0f946c21a5a767d9af916c27df6"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff6c92052b222b2ed31b0d95810dd9a5ca2edf8cc7b8240fd85ae868e63158a5"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecc5e19d6eb1536810834478636d3f58048cf038cad235be3e70a0be5158ed7d"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "unarr"
  desc "Self-hosted media manager, player and debrid agent CLI"
  homepage "https://unarr.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unarr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
