# This file was generated by GoReleaser. DO NOT EDIT.
cask "unarr" do
  version "1.11.1"

  on_macos do
    on_intel do
      sha256 "07d3645369b7455518d39f174e7d01a5f53f6fec73e9f529ba3121af89b70c21"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4598377528e6144f159c61654604baeb7da3721482cccd990e5c0f6bc485dd0e"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fdc749839336fb4e03c6ed7f261667f3ee5febd9f5bbc2a60b98d1de0077487d"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c59e30d5defb1e9de86e9ea8d4d2c163f05a0a17afd0dfe2543350ac221fb38d"
      url "https://github.com/Unarr-app/unarr-cli/releases/download/v#{version}/unarr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "unarr"
  desc "Self-hosted media manager, player and debrid agent CLI"
  homepage "https://unarr.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unarr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
